                                 

GROQ_API_KEY=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

SUPABASE_URL=https://avsyuijyydmihrlaxpcu/

SUPABASE_KEY=sb_publishable_BDi9DOdPsGhLKZetOg3yXQ_twQVS7mK

WP_URL=https://polyplas.cl/

WP_USER=fnac1525

WP_APP_PASSWORD=XrmZG2026@01

GSC_SITE_URL=https://polyplas.cl/
name: Agente SEO

on:
  schedule:
    - cron: '0 8 * * 1'  # cada lunes a las 8am
  workflow_dispatch:      # también puedes ejecutarlo manualmente

jobs:
  analizar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install groq supabase requests python-dotenv rich

      - name: Ejecutar agente
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          GSC_SITE_URL: ${{ secrets.GSC_SITE_URL }}
        run: python3 -c "from crawlers.wordpress import crawl_wordpress; from database import save_pages; from agents.seo_agent import analizar_sitio_completo; save_pages(crawl_wordpress()); analizar_sitio_completo()"

